export enum TxType {
  Creation = 'creation',
  Activation = 'activation',
  GiftTokenReceipt = 'gift_token_receipt',
  Donation = 'donation',
  AddGift = 'add_gift',
  FeePayment = 'fee_payment',
  PrizeCreation = 'prize_creation',
  GiftUnwrap = 'gift_unwrap',
  FinalPrize = 'final_prize',
  Failure = 'failure',
  WinnerRemoval = 'winner_removal',
  GiftReturn = 'gift_return',
  ForwardToTicketRedeem = 'forward_to_ticket_redeem',
  TicketRedeem = 'ticket_redeem',
  ReturnRaffleLicense = 'return_raffle_license',
  SafeWithdrawal = 'safe_withdrawal',
  RedeemProxy = 'redeem_proxy',
}
