import { BlockEntity, PROCEED } from '@rosen-bridge/abstract-scanner';

import {
  InactiveRaffleEntity,
  RaffleDetailsEntity,
  GiftEntity,
  TicketEntity,
  SuccessRaffleEntity,
  GiftRedeemEntity,
  WinnerEntity,
  SafePayEntity,
  TicketRedeemEntity,
} from '@ergo-raffle/extractors';

import { ActivityWithTimeView } from '../lib';
import { createDatabase } from './utils.mock';

export const mockRaffles = async () => {
  const dataSource = await createDatabase();
  const inactiveRaffleRepository =
    dataSource.getRepository(InactiveRaffleEntity);
  const raffleDetailsRepository = dataSource.getRepository(RaffleDetailsEntity);
  const giftRepository = dataSource.getRepository(GiftEntity);
  const ticketRepository = dataSource.getRepository(TicketEntity);
  const successRaffleRepository = dataSource.getRepository(SuccessRaffleEntity);
  const giftRedeemRepository = dataSource.getRepository(GiftRedeemEntity);
  const winnerRepository = dataSource.getRepository(WinnerEntity);

  const raffles = [
    {
      txId: 'tx1_hash_random_string_abc123',
      raffleId: 'raffle1',
      serviceErgoTree: 'tree1_service_ergo_hash_xyz',
      implementerErgoTree: 'tree1_implementer_ergo_hash_abc',
      projectErgoTree: 'tree1_project_ergo_hash_def',
      serviceFeePercent: 5,
      implementerFeePercent: 3,
      winnersPercent: 92,
      ticketPrice: BigInt(1000000000),
      goal: BigInt(1000000000000),
      deadline: 1234567890,
      winnersPercentList: '400,300,0,100,200',
      txFee: BigInt(5000000),
      block: '1000',
      height: 1000,
      extractor: 'raffle_extractor',
      identifier: 'id1',
      serialized: 'serialized1',
    },
    {
      txId: 'tx2_hash_random_string_def456',
      raffleId: 'raffle2',
      serviceErgoTree: 'tree2_service_ergo_hash_ghi',
      implementerErgoTree: 'tree2_implementer_ergo_hash_jkl',
      projectErgoTree: 'tree2_project_ergo_hash_mno',
      serviceFeePercent: 7,
      implementerFeePercent: 4,
      winnersPercent: 89,
      ticketPrice: BigInt(2000000000),
      goal: BigInt(2000000000000),
      deadline: 1234567900,
      winnersPercentList: '500,400,100,100,100',
      txFee: BigInt(6000000),
      collectingTokenId: 'token123',
      block: '2000',
      height: 2000,
      extractor: 'raffle_extractor',
      identifier: 'id2',
      serialized: 'serialized2',
    },
    {
      txId: 'tx3_hash_random_string_ghi789',
      raffleId: 'raffle3',
      serviceErgoTree: 'tree3_service_ergo_hash_pqr',
      implementerErgoTree: 'tree3_implementer_ergo_hash_stu',
      projectErgoTree: 'tree3_project_ergo_hash_vwx',
      serviceFeePercent: 6,
      implementerFeePercent: 3,
      winnersPercent: 91,
      ticketPrice: BigInt(1500000000),
      goal: BigInt(1500000000000),
      deadline: 1234567910,
      winnersPercentList: '450,350,100,100,100',
      txFee: BigInt(5500000),
      block: '3000',
      height: 3000,
      extractor: 'raffle_extractor',
      identifier: 'id3',
      serialized: 'serialized3',
    },
    {
      txId: 'tx4_hash_random_string_jkl012',
      raffleId: 'raffle4',
      serviceErgoTree: 'tree4_service_ergo_hash_yz1',
      implementerErgoTree: 'tree4_implementer_ergo_hash_234',
      projectErgoTree: 'tree4_project_ergo_hash_567',
      serviceFeePercent: 8,
      implementerFeePercent: 5,
      winnersPercent: 87,
      ticketPrice: BigInt(3000000000),
      goal: BigInt(3000000000000),
      deadline: 1234567920,
      winnersPercentList: '600,500,100,100,100',
      txFee: BigInt(7000000),
      block: '4000',
      height: 4000,
      extractor: 'raffle_extractor',
      identifier: 'id4',
      serialized: 'serialized4',
    },
    {
      txId: 'tx5_hash_random_string_mno345',
      raffleId: 'raffle5',
      serviceErgoTree: 'tree5_service_ergo_hash_890',
      implementerErgoTree: 'tree5_implementer_ergo_hash_abc1',
      projectErgoTree: 'tree5_project_ergo_hash_def2',
      serviceFeePercent: 4,
      implementerFeePercent: 2,
      winnersPercent: 94,
      ticketPrice: BigInt(800000000),
      goal: BigInt(800000000000),
      deadline: 1234567930,
      winnersPercentList: '350,250,100,100,100',
      txFee: BigInt(4500000),
      collectingTokenId: 'token123',
      block: '5000',
      height: 5000,
      extractor: 'raffle_extractor',
      identifier: 'id5',
      serialized: 'serialized5',
    },
    {
      txId: 'tx6_hash_random_string_pqr678',
      raffleId: 'raffle6',
      serviceErgoTree: 'tree6_service_ergo_hash_ghi3',
      implementerErgoTree: 'tree6_implementer_ergo_hash_jkl4',
      projectErgoTree: 'tree6_project_ergo_hash_mno5',
      serviceFeePercent: 5,
      implementerFeePercent: 3,
      winnersPercent: 92,
      ticketPrice: BigInt(1200000000),
      goal: BigInt(1200000000000),
      deadline: 1234567940,
      winnersPercentList: '420,320,100,100,100',
      txFee: BigInt(5800000),
      block: '6000',
      height: 6000,
      extractor: 'raffle_extractor',
      identifier: 'id6',
      serialized: 'serialized6',
    },
    {
      txId: 'tx7_hash_random_string_stu901',
      raffleId: 'raffle7',
      serviceErgoTree: 'tree7_service_ergo_hash_vwx6',
      implementerErgoTree: 'tree7_implementer_ergo_hash_yz7',
      projectErgoTree: 'tree7_project_ergo_hash_1238',
      serviceFeePercent: 6,
      implementerFeePercent: 4,
      winnersPercent: 90,
      ticketPrice: BigInt(1800000000),
      goal: BigInt(1800000000000),
      deadline: 1234567950,
      winnersPercentList: '480,380,100,100,100',
      txFee: BigInt(6200000),
      block: '7000',
      height: 7000,
      extractor: 'raffle_extractor',
      identifier: 'id7',
      serialized: 'serialized7',
    },
    {
      txId: 'tx8_hash_random_string_vwx234',
      raffleId: 'raffle8',
      serviceErgoTree: 'tree8_service_ergo_hash_4569',
      implementerErgoTree: 'tree8_implementer_ergo_hash_7890',
      projectErgoTree: 'tree8_project_ergo_hash_abcde',
      serviceFeePercent: 7,
      implementerFeePercent: 3,
      winnersPercent: 90,
      ticketPrice: BigInt(2500000000),
      goal: BigInt(2500000000000),
      deadline: 1234567960,
      winnersPercentList: '550,450,100,100,100',
      txFee: BigInt(6500000),
      collectingTokenId: 'token123',
      block: '8000',
      height: 8000,
      extractor: 'raffle_extractor',
      identifier: 'id8',
      serialized: 'serialized8',
    },
  ];
  const raffleDetails = [
    {
      txId: 'tx1_hash_random_string_abc123',
      raffleId: 'raffle1',
      name: 'Charity Raffle for Education',
      description:
        'Support educational programs for underprivileged children in rural areas. Your contribution helps build schools and provide learning materials.',
      tags: ',charity,education,community,',
      pictures:
        'https://example.com/charity1.jpg,https://example.com/charity2.jpg',
      block: '1000',
      height: 1000,
      extractor: 'raffle_details_extractor',
      identifier: 'details_id1',
      serialized: 'serialized_details1',
    },
    {
      txId: 'tx2_hash_random_string_def456',
      raffleId: 'raffle2',
      name: 'Tech Gadgets Prize Draw',
      description:
        'Win the latest smartphones, laptops, and gaming consoles. Perfect for tech enthusiasts looking to upgrade their devices.',
      tags: ',tech,gadgets,electronics,prize,the-test-tag,',
      pictures: 'https://example.com/tech1.jpg,https://example.com/tech2.jpg',
      block: '2000',
      height: 2000,
      extractor: 'raffle_details_extractor',
      identifier: 'details_id2',
      serialized: 'serialized_details2',
    },
    {
      txId: 'tx3_hash_random_string_ghi789',
      raffleId: 'raffle3',
      name: 'Community Development Project',
      description:
        'Help fund local community centers, parks, and recreational facilities. Building stronger neighborhoods together.',
      tags: ',community,local,development,',
      pictures:
        'https://example.com/community1.jpg,https://example.com/community2.jpg',
      block: '3000',
      height: 3000,
      extractor: 'raffle_details_extractor',
      identifier: 'details_id3',
      serialized: 'serialized_details3',
    },
    {
      txId: 'tx4_hash_random_string_jkl012',
      raffleId: 'raffle4',
      name: 'Tech@gadget.com Exclusive Raffle',
      description:
        'Exclusive raffle for tech gadget enthusiasts. Premium devices and accessories from top brands.',
      tags: ',tech,gadgets,exclusive,premium,the-test-tag,',
      pictures:
        'https://example.com/gadget1.jpg,https://example.com/gadget2.jpg',
      block: '4000',
      height: 4000,
      extractor: 'raffle_details_extractor',
      identifier: 'details_id4',
      serialized: 'serialized_details4',
    },
    {
      txId: 'tx5_hash_random_string_mno345',
      raffleId: 'raffle5',
      name: 'Charity Event for Healthcare',
      description:
        'Support healthcare initiatives in developing countries. Your ticket helps provide medical supplies and treatments.',
      tags: ',charity,healthcare,medical,help,',
      pictures:
        'https://example.com/health1.jpg,https://example.com/health2.jpg',
      block: '5000',
      height: 5000,
      extractor: 'raffle_details_extractor',
      identifier: 'details_id5',
      serialized: 'serialized_details5',
    },
    {
      txId: 'tx6_hash_random_string_pqr678',
      raffleId: 'raffle6',
      name: 'Tech Gadgets Innovation Prize',
      description:
        'Win cutting-edge technology and innovative gadgets. From smart home devices to wearable tech.',
      tags: ',tech,gadgets,innovation,smart,',
      pictures: 'https://example.com/innov1.jpg,https://example.com/innov2.jpg',
      block: '6000',
      height: 6000,
      extractor: 'raffle_details_extractor',
      identifier: 'details_id6',
      serialized: 'serialized_details6',
    },
    {
      txId: 'tx7_hash_random_string_stu901',
      raffleId: 'raffle7',
      name: 'Successful Charity Campaign',
      description:
        'A proven track record of successful charitable initiatives. Join our community of givers making real impact.',
      tags: ',charity,successful,impact,giving,',
      pictures:
        'https://example.com/success1.jpg,https://example.com/success2.jpg',
      block: '7000',
      height: 7000,
      extractor: 'raffle_details_extractor',
      identifier: 'details_id7',
      serialized: 'serialized_details7',
    },
    {
      txId: 'tx8_hash_random_string_vwx234',
      raffleId: 'raffle8',
      name: 'Active Tech Competition',
      description:
        'Compete for amazing tech prizes in this ongoing competition. Multiple rounds and exciting challenges await.',
      tags: ',tech,competition,active,challenges,',
      pictures: 'https://example.com/comp1.jpg,https://example.com/comp2.jpg',
      block: '8000',
      height: 8000,
      extractor: 'raffle_details_extractor',
      identifier: 'details_id8',
      serialized: 'serialized_details8',
    },
  ];

  const gifts = [
    {
      txId: 'gift_tx1_1',
      raffleId: 'raffle1',
      donatorErgoTree: 'donator_tree1_1',
      winnerIndex: 0,
      block: '1000',
      height: 1000,
      extractor: 'gift_extractor',
      identifier: 'gift_id1',
      serialized: 'serialized_gift1',
    },
    {
      txId: 'gift_tx1_2',
      raffleId: 'raffle1',
      donatorErgoTree: 'donator_tree1_2',
      winnerIndex: 1,
      block: '1000',
      height: 1000,
      extractor: 'gift_extractor',
      identifier: 'gift_id2',
      serialized: 'serialized_gift2',
    },
    {
      txId: 'gift_tx1_3',
      raffleId: 'raffle1',
      donatorErgoTree: 'donator_tree1_3',
      winnerIndex: 2,
      block: '1000',
      height: 1000,
      extractor: 'gift_extractor',
      identifier: 'gift_id3',
      serialized: 'serialized_gift3',
    },
    {
      txId: 'gift_tx2_1',
      raffleId: 'raffle2',
      donatorErgoTree: 'donator_tree2_1',
      winnerIndex: 0,
      block: '2000',
      height: 2000,
      extractor: 'gift_extractor',
      identifier: 'gift_id4',
      serialized: 'serialized_gift4',
    },
    {
      txId: 'gift_tx2_2',
      raffleId: 'raffle2',
      donatorErgoTree: 'donator_tree2_2',
      winnerIndex: 1,
      block: '2000',
      height: 2000,
      extractor: 'gift_extractor',
      identifier: 'gift_id5',
      serialized: 'serialized_gift5',
    },
    {
      txId: 'gift_tx3_1',
      raffleId: 'raffle3',
      donatorErgoTree: 'donator_tree3_1',
      winnerIndex: 0,
      block: '3000',
      height: 3000,
      extractor: 'gift_extractor',
      identifier: 'gift_id6',
      serialized: 'serialized_gift6',
    },
    {
      txId: 'gift_tx3_2',
      raffleId: 'raffle3',
      donatorErgoTree: 'donator_tree3_2',
      winnerIndex: 1,
      block: '3000',
      height: 3000,
      extractor: 'gift_extractor',
      identifier: 'gift_id7',
      serialized: 'serialized_gift7',
    },
    {
      txId: 'gift_tx3_3',
      raffleId: 'raffle3',
      donatorErgoTree: 'donator_tree3_3',
      winnerIndex: 2,
      block: '3000',
      height: 3000,
      extractor: 'gift_extractor',
      identifier: 'gift_id8',
      serialized: 'serialized_gift8',
    },
    {
      txId: 'gift_tx3_4',
      raffleId: 'raffle3',
      donatorErgoTree: 'donator_tree3_4',
      winnerIndex: 3,
      block: '3000',
      height: 3000,
      extractor: 'gift_extractor',
      identifier: 'gift_id9',
      serialized: 'serialized_gift9',
    },
    {
      txId: 'gift_tx4_1',
      raffleId: 'raffle4',
      donatorErgoTree: 'donator_tree4_1',
      winnerIndex: 0,
      block: '4000',
      height: 4000,
      extractor: 'gift_extractor',
      identifier: 'gift_id10',
      serialized: 'serialized_gift10',
    },
    {
      txId: 'gift_tx4_2',
      raffleId: 'raffle4',
      donatorErgoTree: 'donator_tree4_2',
      winnerIndex: 1,
      block: '4000',
      height: 4000,
      extractor: 'gift_extractor',
      identifier: 'gift_id11',
      serialized: 'serialized_gift11',
    },
    {
      txId: 'gift_tx5_1',
      raffleId: 'raffle5',
      donatorErgoTree: 'donator_tree5_1',
      winnerIndex: 0,
      block: '5000',
      height: 5000,
      extractor: 'gift_extractor',
      identifier: 'gift_id12',
      serialized: 'serialized_gift12',
    },
    {
      txId: 'gift_tx6_1',
      raffleId: 'raffle6',
      donatorErgoTree: 'donator_tree6_1',
      winnerIndex: 0,
      block: '6000',
      height: 6000,
      extractor: 'gift_extractor',
      identifier: 'gift_id13',
      serialized: 'serialized_gift13',
    },
    {
      txId: 'gift_tx6_2',
      raffleId: 'raffle6',
      donatorErgoTree: 'donator_tree6_2',
      winnerIndex: 1,
      block: '6000',
      height: 6000,
      extractor: 'gift_extractor',
      identifier: 'gift_id14',
      serialized: 'serialized_gift14',
    },
    {
      txId: 'gift_tx6_3',
      raffleId: 'raffle6',
      donatorErgoTree: 'donator_tree6_3',
      winnerIndex: 2,
      block: '6000',
      height: 6000,
      extractor: 'gift_extractor',
      identifier: 'gift_id15',
      serialized: 'serialized_gift15',
    },
    {
      txId: 'gift_tx8_1',
      raffleId: 'raffle8',
      donatorErgoTree: 'donator_tree8_1',
      winnerIndex: 0,
      block: '8000',
      height: 8000,
      extractor: 'gift_extractor',
      identifier: 'gift_id16',
      serialized: 'serialized_gift16',
    },
    {
      txId: 'gift_tx8_2',
      raffleId: 'raffle8',
      donatorErgoTree: 'donator_tree8_2',
      winnerIndex: 1,
      block: '8000',
      height: 8000,
      extractor: 'gift_extractor',
      identifier: 'gift_id17',
      serialized: 'serialized_gift17',
    },
    {
      txId: 'gift_tx8_3',
      raffleId: 'raffle8',
      donatorErgoTree: 'donator_tree8_3',
      winnerIndex: 2,
      block: '8000',
      height: 8000,
      extractor: 'gift_extractor',
      identifier: 'gift_id18',
      serialized: 'serialized_gift18',
    },
    {
      txId: 'gift_tx8_4',
      raffleId: 'raffle8',
      donatorErgoTree: 'donator_tree8_4',
      winnerIndex: 3,
      block: '8000',
      height: 8000,
      extractor: 'gift_extractor',
      identifier: 'gift_id19',
      serialized: 'serialized_gift19',
    },
    {
      txId: 'gift_tx8_5',
      raffleId: 'raffle8',
      donatorErgoTree: 'donator_tree8_5',
      winnerIndex: 4,
      block: '8000',
      height: 8000,
      extractor: 'gift_extractor',
      identifier: 'gift_id20',
      serialized: 'serialized_gift20',
    },
  ];

  const tickets = [
    {
      txId: 'ticket_tx1_1',
      raffleId: 'raffle1',
      donatorErgoTree: 'donator_tree1_1',
      rangeStart: BigInt(1),
      rangeEnd: BigInt(10),
      block: '1000',
      height: 1000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id1',
      serialized: 'serialized_ticket1',
    },
    {
      txId: 'ticket_tx1_2',
      raffleId: 'raffle1',
      donatorErgoTree: 'donator_tree1_2',
      rangeStart: BigInt(11),
      rangeEnd: BigInt(20),
      block: '1000',
      height: 1000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id2',
      serialized: 'serialized_ticket2',
    },
    {
      txId: 'ticket_tx1_3',
      raffleId: 'raffle1',
      donatorErgoTree: 'donator_tree1_3',
      rangeStart: BigInt(21),
      rangeEnd: BigInt(30),
      block: '1000',
      height: 1000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id3',
      serialized: 'serialized_ticket3',
    },
    {
      txId: 'ticket_tx2_1',
      raffleId: 'raffle2',
      donatorErgoTree: 'donator_tree2_1',
      rangeStart: BigInt(1),
      rangeEnd: BigInt(15),
      block: '2000',
      height: 2000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id4',
      serialized: 'serialized_ticket4',
    },
    {
      txId: 'ticket_tx2_2',
      raffleId: 'raffle2',
      donatorErgoTree: 'donator_tree2_2',
      rangeStart: BigInt(16),
      rangeEnd: BigInt(30),
      block: '2000',
      height: 2000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id5',
      serialized: 'serialized_ticket5',
    },
    {
      txId: 'ticket_tx3_1',
      raffleId: 'raffle3',
      donatorErgoTree: 'donator_tree3_1',
      rangeStart: BigInt(1),
      rangeEnd: BigInt(20),
      block: '3000',
      height: 3000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id6',
      serialized: 'serialized_ticket6',
    },
    {
      txId: 'ticket_tx3_2',
      raffleId: 'raffle3',
      donatorErgoTree: 'donator_tree3_2',
      rangeStart: BigInt(21),
      rangeEnd: BigInt(40),
      block: '3000',
      height: 3000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id7',
      serialized: 'serialized_ticket7',
    },
    {
      txId: 'ticket_tx3_3',
      raffleId: 'raffle3',
      donatorErgoTree: 'donator_tree3_3',
      rangeStart: BigInt(41),
      rangeEnd: BigInt(60),
      block: '3000',
      height: 3000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id8',
      serialized: 'serialized_ticket8',
    },
    {
      txId: 'ticket_tx3_4',
      raffleId: 'raffle3',
      donatorErgoTree: 'donator_tree3_4',
      rangeStart: BigInt(61),
      rangeEnd: BigInt(80),
      block: '3000',
      height: 3000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id9',
      serialized: 'serialized_ticket9',
    },
    {
      txId: 'ticket_tx4_1',
      raffleId: 'raffle4',
      donatorErgoTree: 'donator_tree4_1',
      rangeStart: BigInt(1),
      rangeEnd: BigInt(25),
      block: '4000',
      height: 4000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id10',
      serialized: 'serialized_ticket10',
    },
    {
      txId: 'ticket_tx4_2',
      raffleId: 'raffle4',
      donatorErgoTree: 'donator_tree4_2',
      rangeStart: BigInt(26),
      rangeEnd: BigInt(50),
      block: '4000',
      height: 4000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id11',
      serialized: 'serialized_ticket11',
    },
    {
      txId: 'ticket_tx5_1',
      raffleId: 'raffle5',
      donatorErgoTree: 'donator_tree5_1',
      rangeStart: BigInt(1),
      rangeEnd: BigInt(10),
      block: '5000',
      height: 5000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id12',
      serialized: 'serialized_ticket12',
    },
    {
      txId: 'ticket_tx6_1',
      raffleId: 'raffle6',
      donatorErgoTree: 'donator_tree6_1',
      rangeStart: BigInt(1),
      rangeEnd: BigInt(15),
      block: '6000',
      height: 6000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id13',
      serialized: 'serialized_ticket13',
    },
    {
      txId: 'ticket_tx6_2',
      raffleId: 'raffle6',
      donatorErgoTree: 'donator_tree6_2',
      rangeStart: BigInt(16),
      rangeEnd: BigInt(30),
      block: '6000',
      height: 6000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id14',
      serialized: 'serialized_ticket14',
    },
    {
      txId: 'ticket_tx6_3',
      raffleId: 'raffle6',
      donatorErgoTree: 'donator_tree6_3',
      rangeStart: BigInt(31),
      rangeEnd: BigInt(45),
      block: '6000',
      height: 6000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id15',
      serialized: 'serialized_ticket15',
    },
    {
      txId: 'ticket_tx7_1',
      raffleId: 'raffle7',
      donatorErgoTree: 'donator_tree7_1',
      rangeStart: BigInt(1),
      rangeEnd: BigInt(20),
      block: '7000',
      height: 7000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id16',
      serialized: 'serialized_ticket16',
    },
    {
      txId: 'ticket_tx7_2',
      raffleId: 'raffle7',
      donatorErgoTree: 'donator_tree7_2',
      rangeStart: BigInt(21),
      rangeEnd: BigInt(40),
      block: '7000',
      height: 7000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id17',
      serialized: 'serialized_ticket17',
    },
    {
      txId: 'ticket_tx8_1',
      raffleId: 'raffle8',
      donatorErgoTree: 'donator_tree8_1',
      rangeStart: BigInt(1),
      rangeEnd: BigInt(10),
      block: '8000',
      height: 8000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id18',
      serialized: 'serialized_ticket18',
    },
    {
      txId: 'ticket_tx8_2',
      raffleId: 'raffle8',
      donatorErgoTree: 'donator_tree8_2',
      rangeStart: BigInt(11),
      rangeEnd: BigInt(20),
      block: '8000',
      height: 8000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id19',
      serialized: 'serialized_ticket19',
    },
    {
      txId: 'ticket_tx8_3',
      raffleId: 'raffle8',
      donatorErgoTree: 'donator_tree8_3',
      rangeStart: BigInt(21),
      rangeEnd: BigInt(30),
      block: '8000',
      height: 8000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id20',
      serialized: 'serialized_ticket20',
    },
    {
      txId: 'ticket_tx8_4',
      raffleId: 'raffle8',
      donatorErgoTree: 'donator_tree8_4',
      rangeStart: BigInt(31),
      rangeEnd: BigInt(40),
      block: '8000',
      height: 8000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id21',
      serialized: 'serialized_ticket21',
    },
    {
      txId: 'ticket_tx8_5',
      raffleId: 'raffle8',
      donatorErgoTree: 'donator_tree8_5',
      rangeStart: BigInt(41),
      rangeEnd: BigInt(50),
      block: '8000',
      height: 8000,
      extractor: 'ticket_extractor',
      identifier: 'ticket_id22',
      serialized: 'serialized_ticket22',
    },
  ];

  await inactiveRaffleRepository.insert(raffles);
  await raffleDetailsRepository.insert(raffleDetails);
  await giftRepository.insert(gifts);
  await ticketRepository.insert(tickets);

  const winners = [
    {
      txId: 'winner_tx1_0',
      raffleId: 'raffle1',
      index: 0,
      rewardPercent: 400,
      block: '1000',
      height: 1000,
      extractor: 'winner_extractor',
      identifier: 'winner_id1',
      serialized: 'serialized_winner1',
    },
    {
      txId: 'winner_tx1_1',
      raffleId: 'raffle1',
      index: 1,
      rewardPercent: 300,
      block: '1000',
      height: 1000,
      extractor: 'winner_extractor',
      identifier: 'winner_id2',
      serialized: 'serialized_winner2',
    },
    {
      txId: 'winner_tx1_2',
      raffleId: 'raffle1',
      index: 2,
      rewardPercent: 0,
      block: '1000',
      height: 1000,
      extractor: 'winner_extractor',
      identifier: 'winner_id3',
      serialized: 'serialized_winner3',
    },
    {
      txId: 'winner_tx1_3',
      raffleId: 'raffle1',
      index: 3,
      rewardPercent: 100,
      block: '1000',
      height: 1000,
      extractor: 'winner_extractor',
      identifier: 'winner_id4',
      serialized: 'serialized_winner4',
    },
    {
      txId: 'winner_tx1_4',
      raffleId: 'raffle1',
      index: 4,
      rewardPercent: 200,
      block: '1000',
      height: 1000,
      extractor: 'winner_extractor',
      identifier: 'winner_id5',
      serialized: 'serialized_winner5',
    },
    {
      txId: 'winner_tx2_0',
      raffleId: 'raffle2',
      index: 0,
      rewardPercent: 50,
      block: '2000',
      height: 2000,
      extractor: 'winner_extractor',
      identifier: 'winner_id6',
      serialized: 'serialized_winner6',
    },
    {
      txId: 'winner_tx2_1',
      raffleId: 'raffle2',
      index: 1,
      rewardPercent: 40,
      block: '2000',
      height: 2000,
      extractor: 'winner_extractor',
      identifier: 'winner_id7',
      serialized: 'serialized_winner7',
    },
    {
      txId: 'winner_tx2_2',
      raffleId: 'raffle2',
      index: 2,
      rewardPercent: 10,
      block: '2000',
      height: 2000,
      extractor: 'winner_extractor',
      identifier: 'winner_id8',
      serialized: 'serialized_winner8',
    },
    {
      txId: 'winner_tx3_0',
      raffleId: 'raffle3',
      index: 0,
      rewardPercent: 45,
      block: '3000',
      height: 3000,
      extractor: 'winner_extractor',
      identifier: 'winner_id9',
      serialized: 'serialized_winner9',
    },
    {
      txId: 'winner_tx3_1',
      raffleId: 'raffle3',
      index: 1,
      rewardPercent: 35,
      block: '3000',
      height: 3000,
      extractor: 'winner_extractor',
      identifier: 'winner_id10',
      serialized: 'serialized_winner10',
    },
    {
      txId: 'winner_tx3_2',
      raffleId: 'raffle3',
      index: 2,
      rewardPercent: 10,
      block: '3000',
      height: 3000,
      extractor: 'winner_extractor',
      identifier: 'winner_id11',
      serialized: 'serialized_winner11',
    },
    {
      txId: 'winner_tx4_0',
      raffleId: 'raffle4',
      index: 0,
      rewardPercent: 60,
      block: '4000',
      height: 4000,
      extractor: 'winner_extractor',
      identifier: 'winner_id12',
      serialized: 'serialized_winner12',
    },
    {
      txId: 'winner_tx4_1',
      raffleId: 'raffle4',
      index: 1,
      rewardPercent: 50,
      block: '4000',
      height: 4000,
      extractor: 'winner_extractor',
      identifier: 'winner_id13',
      serialized: 'serialized_winner13',
    },
    {
      txId: 'winner_tx4_2',
      raffleId: 'raffle4',
      index: 2,
      rewardPercent: 10,
      block: '4000',
      height: 4000,
      extractor: 'winner_extractor',
      identifier: 'winner_id14',
      serialized: 'serialized_winner14',
    },
    {
      txId: 'winner_tx4_3',
      raffleId: 'raffle4',
      index: 3,
      rewardPercent: 10,
      block: '4000',
      height: 4000,
      extractor: 'winner_extractor',
      identifier: 'winner_id15',
      serialized: 'serialized_winner15',
    },
    {
      txId: 'winner_tx5_0',
      raffleId: 'raffle5',
      index: 0,
      rewardPercent: 35,
      block: '5000',
      height: 5000,
      extractor: 'winner_extractor',
      identifier: 'winner_id16',
      serialized: 'serialized_winner16',
    },
    {
      txId: 'winner_tx5_1',
      raffleId: 'raffle5',
      index: 1,
      rewardPercent: 25,
      block: '5000',
      height: 5000,
      extractor: 'winner_extractor',
      identifier: 'winner_id17',
      serialized: 'serialized_winner17',
    },
    {
      txId: 'winner_tx5_2',
      raffleId: 'raffle5',
      index: 2,
      rewardPercent: 10,
      block: '5000',
      height: 5000,
      extractor: 'winner_extractor',
      identifier: 'winner_id18',
      serialized: 'serialized_winner18',
    },
  ];

  await winnerRepository.insert(winners);

  const successRaffles = [
    {
      txId: 'success_tx1',
      raffleId: 'raffle2',
      selectedWinnersList: '0,1,2',
      step: 1,
      block: '2000',
      height: 2000,
      extractor: 'success_extractor',
      identifier: 'success_id1',
      serialized: 'serialized_success1',
    },
    {
      txId: 'success_tx2',
      raffleId: 'raffle4',
      selectedWinnersList: '0,1,2,3',
      step: 2,
      block: '4000',
      height: 4000,
      extractor: 'success_extractor',
      identifier: 'success_id2',
      serialized: 'serialized_success2',
    },
  ];

  const giftRedeems = [
    {
      txId: 'redeem_tx1',
      raffleId: 'raffle3',
      block: '3000',
      height: 3000,
      step: 0,
      extractor: 'redeem_extractor',
      identifier: 'redeem_id1',
      serialized: 'serialized_redeem1',
    },
    {
      txId: 'redeem_tx2',
      raffleId: 'raffle5',
      block: '5000',
      step: 0,
      height: 5000,
      extractor: 'redeem_extractor',
      identifier: 'redeem_id2',
      serialized: 'serialized_redeem2',
    },
  ];

  await successRaffleRepository.insert(successRaffles);
  await giftRedeemRepository.insert(giftRedeems);
  return dataSource;
};

export const mockActivities = async () => {
  const dataSource = await createDatabase();
  const inactiveRaffleRepository =
    dataSource.getRepository(InactiveRaffleEntity);
  const ticketRepository = dataSource.getRepository(TicketEntity);
  const giftRepository = dataSource.getRepository(GiftEntity);
  const safePayRepository = dataSource.getRepository(SafePayEntity);
  const ticketRedeemRepository = dataSource.getRepository(TicketRedeemEntity);
  const giftRedeemRepository = dataSource.getRepository(GiftRedeemEntity);
  const blockRepository = dataSource.getRepository(BlockEntity);

  // addr_user1 creates raffle1 and raffle3
  // addr_user2 creates raffle2
  const raffles = [
    {
      txId: 'raffle_tx1',
      raffleId: 'raffle1',
      serviceErgoTree: 'service_tree1',
      implementerErgoTree: 'impl_tree1',
      projectErgoTree: 'addr_user1',
      serviceFeePercent: 5,
      implementerFeePercent: 3,
      winnersPercent: 92,
      ticketPrice: BigInt(1000000000),
      goal: BigInt(1000000000000),
      deadline: 100,
      winnersPercentList: '400,300,100,100,100',
      txFee: BigInt(5000000),
      block: '1000',
      height: 1000,
      extractor: 'raffle_extractor',
      identifier: 'act_raffle_id1',
      serialized: 'act_serialized1',
    },
    {
      txId: 'raffle_tx2',
      raffleId: 'raffle2',
      serviceErgoTree: 'service_tree2',
      implementerErgoTree: 'impl_tree2',
      projectErgoTree: 'addr_user2',
      serviceFeePercent: 5,
      implementerFeePercent: 3,
      winnersPercent: 92,
      ticketPrice: BigInt(1000000000),
      goal: BigInt(1000000000000),
      deadline: 200,
      winnersPercentList: '400,300,100,100,100',
      txFee: BigInt(5000000),
      block: '2000',
      height: 2000,
      extractor: 'raffle_extractor',
      identifier: 'act_raffle_id2',
      serialized: 'act_serialized2',
    },
    {
      txId: 'raffle_tx3',
      raffleId: 'raffle3',
      serviceErgoTree: 'service_tree3',
      implementerErgoTree: 'impl_tree3',
      projectErgoTree: 'addr_user1',
      serviceFeePercent: 5,
      implementerFeePercent: 3,
      winnersPercent: 92,
      ticketPrice: BigInt(1000000000),
      goal: BigInt(1000000000000),
      deadline: 300,
      winnersPercentList: '400,300,100,100,100',
      txFee: BigInt(5000000),
      block: '3000',
      height: 3000,
      extractor: 'raffle_extractor',
      identifier: 'act_raffle_id3',
      serialized: 'act_serialized3',
    },
  ];

  // addr_user2 buys 5 tickets in raffle1
  // addr_user1 buys 3 tickets in raffle2
  // addr_user3 buys 1 ticket in raffle1
  const tickets = [
    {
      txId: 'ticket_tx1',
      raffleId: 'raffle1',
      donatorErgoTree: 'addr_user2',
      rangeStart: BigInt(0),
      rangeEnd: BigInt(5),
      block: '1000',
      height: 1000,
      extractor: 'ticket_extractor',
      identifier: 'act_ticket_id1',
      serialized: 'act_ticket_serialized1',
    },
    {
      txId: 'ticket_tx2',
      raffleId: 'raffle2',
      donatorErgoTree: 'addr_user1',
      rangeStart: BigInt(0),
      rangeEnd: BigInt(3),
      block: '2000',
      height: 2000,
      extractor: 'ticket_extractor',
      identifier: 'act_ticket_id2',
      serialized: 'act_ticket_serialized2',
    },
    {
      txId: 'ticket_tx3',
      raffleId: 'raffle1',
      donatorErgoTree: 'addr_user3',
      rangeStart: BigInt(5),
      rangeEnd: BigInt(6),
      block: '1000',
      height: 1000,
      extractor: 'ticket_extractor',
      identifier: 'act_ticket_id3',
      serialized: 'act_ticket_serialized3',
    },
  ];

  // addr_user1 adds a gift to raffle1
  // addr_user3 adds a gift to raffle3
  const gifts = [
    {
      txId: 'gift_tx1',
      raffleId: 'raffle1',
      donatorErgoTree: 'addr_user1',
      winnerIndex: 0,
      block: '1000',
      height: 1000,
      extractor: 'gift_extractor',
      identifier: 'act_gift_id1',
      serialized: 'act_gift_serialized1',
    },
    {
      txId: 'gift_tx2',
      raffleId: 'raffle3',
      donatorErgoTree: 'addr_user3',
      winnerIndex: 0,
      block: '3000',
      height: 3000,
      extractor: 'gift_extractor',
      identifier: 'act_gift_id2',
      serialized: 'act_gift_serialized2',
    },
  ];

  // addr_user1 redeems ticket_tx2 (raffle2, 3 tickets) -> safepay_tx1
  // addr_user3 redeems ticket_tx3 (raffle1, 1 ticket) -> safepay_tx2
  // addr_user1 returns gift_tx1 (raffle1) -> safepay_tx3
  // addr_user3 returns gift_tx2 (raffle3) -> safepay_tx4
  // an extra safe_pay row (other_tx_no_redeem) joins ticket_tx1 but has
  // no matching TicketRedeemEntity / GiftRedeemEntity, so it must NOT
  // surface as an activity
  const safePays = [
    {
      txId: 'safepay_tx1',
      inputBoxId: 'act_ticket_id2',
      recipient: 'addr_user1',
      block: '2500',
      height: 2500,
      extractor: 'safe_pay_extractor',
      identifier: 'act_safepay_id1',
      serialized: 'act_safepay_serialized1',
    },
    {
      txId: 'safepay_tx2',
      inputBoxId: 'act_ticket_id3',
      recipient: 'addr_user3',
      block: '1100',
      height: 1100,
      extractor: 'safe_pay_extractor',
      identifier: 'act_safepay_id2',
      serialized: 'act_safepay_serialized2',
    },
    {
      txId: 'safepay_tx3',
      inputBoxId: 'act_gift_id1',
      recipient: 'addr_user1',
      block: '1500',
      height: 1500,
      extractor: 'safe_pay_extractor',
      identifier: 'act_safepay_id3',
      serialized: 'act_safepay_serialized3',
    },
    {
      txId: 'safepay_tx4',
      inputBoxId: 'act_gift_id2',
      recipient: 'addr_user3',
      block: '3500',
      height: 3500,
      extractor: 'safe_pay_extractor',
      identifier: 'act_safepay_id4',
      serialized: 'act_safepay_serialized4',
    },
    {
      txId: 'other_tx_no_redeem',
      inputBoxId: 'act_ticket_id1',
      recipient: 'addr_user2',
      block: '1200',
      height: 1200,
      extractor: 'safe_pay_extractor',
      identifier: 'act_safepay_id5',
      serialized: 'act_safepay_serialized5',
    },
  ];

  const ticketRedeems = [
    {
      txId: 'safepay_tx1',
      raffleId: 'raffle2',
      totalSoldTicket: BigInt(3),
      redeemedTickets: BigInt(3),
      block: '2500',
      height: 2500,
      extractor: 'ticket_redeem_extractor',
      identifier: 'act_redeem_id1',
      serialized: 'act_redeem_serialized1',
    },
    {
      txId: 'safepay_tx2',
      raffleId: 'raffle1',
      totalSoldTicket: BigInt(6),
      redeemedTickets: BigInt(1),
      block: '1100',
      height: 1100,
      extractor: 'ticket_redeem_extractor',
      identifier: 'act_redeem_id2',
      serialized: 'act_redeem_serialized2',
    },
  ];

  const giftRedeems = [
    {
      txId: 'safepay_tx3',
      raffleId: 'raffle1',
      step: 0,
      block: '1500',
      height: 1500,
      extractor: 'gift_redeem_extractor',
      identifier: 'act_gift_redeem_id1',
      serialized: 'act_gift_redeem_serialized1',
    },
    {
      txId: 'safepay_tx4',
      raffleId: 'raffle3',
      step: 0,
      block: '3500',
      height: 3500,
      extractor: 'gift_redeem_extractor',
      identifier: 'act_gift_redeem_id2',
      serialized: 'act_gift_redeem_serialized2',
    },
  ];

  // For each distinct height referenced in mocked data, insert one block row.
  // This is required for views that join activities with BlockEntity.
  const blockEntries = [
    ...raffles,
    ...tickets,
    ...gifts,
    ...safePays,
    ...ticketRedeems,
    ...giftRedeems,
  ]
    .map((item) => ({ height: item.height, hash: item.block }))
    .filter(
      (item, index, all) =>
        all.findIndex((other) => other.height === item.height) === index,
    )
    .map((item) => ({
      height: item.height,
      hash: String(item.hash),
      parentHash: `parent_${item.height}`,
      status: PROCEED,
      scanner: 'ergo',
      timestamp: item.height * 1000,
    }));

  await inactiveRaffleRepository.insert(raffles);
  await blockRepository.insert(blockEntries);
  await ticketRepository.insert(tickets);
  await giftRepository.insert(gifts);
  await safePayRepository.insert(safePays);
  await ticketRedeemRepository.insert(ticketRedeems);
  await giftRedeemRepository.insert(giftRedeems);
  return dataSource;
};

// Expected activity view rows sorted by txId for use in tests
export const activityItems: Partial<ActivityWithTimeView>[] = [
  {
    ergoTree: 'addr_user1',
    raffleId: 'raffle1',
    type: 'gift',
    txId: 'gift_tx1',
    height: 1000,
    timestamp: 1000000,
    ticketCount: 0n,
  },
  {
    ergoTree: 'addr_user3',
    raffleId: 'raffle3',
    type: 'gift',
    txId: 'gift_tx2',
    height: 3000,
    timestamp: 3000000,
    ticketCount: 0n,
  },
  {
    ergoTree: 'addr_user1',
    raffleId: 'raffle1',
    type: 'creation',
    txId: 'raffle_tx1',
    height: 1000,
    timestamp: 1000000,
    ticketCount: 0n,
  },
  {
    ergoTree: 'addr_user2',
    raffleId: 'raffle2',
    type: 'creation',
    txId: 'raffle_tx2',
    height: 2000,
    timestamp: 2000000,
    ticketCount: 0n,
  },
  {
    ergoTree: 'addr_user1',
    raffleId: 'raffle3',
    type: 'creation',
    txId: 'raffle_tx3',
    height: 3000,
    timestamp: 3000000,
    ticketCount: 0n,
  },
  {
    ergoTree: 'addr_user1',
    raffleId: 'raffle2',
    type: 'ticket_redeem',
    txId: 'safepay_tx1',
    height: 2500,
    timestamp: 2500000,
    ticketCount: 3n,
  },
  {
    ergoTree: 'addr_user3',
    raffleId: 'raffle1',
    type: 'ticket_redeem',
    txId: 'safepay_tx2',
    height: 1100,
    timestamp: 1100000,
    ticketCount: 1n,
  },
  {
    ergoTree: 'addr_user1',
    raffleId: 'raffle1',
    type: 'gift_return',
    txId: 'safepay_tx3',
    height: 1500,
    timestamp: 1500000,
    ticketCount: 0n,
  },
  {
    ergoTree: 'addr_user3',
    raffleId: 'raffle3',
    type: 'gift_return',
    txId: 'safepay_tx4',
    height: 3500,
    timestamp: 3500000,
    ticketCount: 0n,
  },
  {
    ergoTree: 'addr_user2',
    raffleId: 'raffle1',
    type: 'donation',
    txId: 'ticket_tx1',
    height: 1000,
    timestamp: 1000000,
    ticketCount: 5n,
  },
  {
    ergoTree: 'addr_user1',
    raffleId: 'raffle2',
    type: 'donation',
    txId: 'ticket_tx2',
    height: 2000,
    timestamp: 2000000,
    ticketCount: 3n,
  },
  {
    ergoTree: 'addr_user3',
    raffleId: 'raffle1',
    type: 'donation',
    txId: 'ticket_tx3',
    height: 1000,
    timestamp: 1000000,
    ticketCount: 1n,
  },
];
