logs:
  - type: console
    level: info
  - type: file
    level: info
    path: ./logs/
    maxSize: 20m
    maxFiles: 14d
database:
  type: sqlite
  path: ./db.sqlite3
api:
  host: localhost
  port: 8800
ipfs:
  urlTransformSchema: https://ipfs.io/ipfs/{CID}
