logs:
  - type: console
    level: info
  - type: file
    maxSize: 20m
    maxFiles: 14d
    path: ./logs/
    level: debug
database:
  type: 'sqlite'
  path: 'job.sqlite'
scanner:
  node:
    url: 'http://176.9.15.237:9052/'
    timeout: 1000000
    initialHeight: 1689162
